### ISSUE TITLE
Comply to awesome-lint

### ISSUE THREAD

**Issue by dar5hak** [dar5hak/generator-awesome-list#14]
Make sure that the generated files comply to https://github.com/sindresorhus/awesome-lint to the extent possible for a generator

**Comment by dar5hak** [comment]
# Update

Tried running `awesome-lint` in the `app/templates` directory. No output.

**Comment by sindresorhus** [comment]
> Update: Tried running awesome-lint in the app/templates directory. No output.

Probably because there's a lot of invalid markdown due to the template tags. Try running it on the generated output instead.

**Comment by dar5hak** [comment]
@sindresorhus Good idea. I'll add it to the test spec directly. Thanks. 👍

**Comment by dar5hak** [comment]
And it's done,

**Comment by koyulin24747-arch** [comment]
I was thinking of no more new adjusts of new Claude and the newest that 4.7  is dinne doing well,not been trained by me or learning of my style and command!
