### ISSUE TITLE
Reference to RichardLitt/docs/amending-a-commit-guide.md gives 404

### ISSUE THREAD

**Issue by hussfelt** [dar5hak/generator-awesome-list#26]
Seems like RichardLitt has removed that repository.

https://github.com/RichardLitt/docs/blob/master/amending-a-commit-guide.md

**Comment by dar5hak** [comment]
Umm, sorry, but I don't understand the context. What are you referring to?

**Comment by hussfelt** [comment]
@dar5hak Sorry, maybe I could have been more clear.

The link you have here: https://github.com/dar5hak/generator-awesome-list/blob/master/app/templates/contributing.md#updating-your-pr

> If you're not sure how to do that, here is a guide on the different ways you can update your PR so that we can merge it.

The guide gives a 404, it no longer exists.

**Comment by dar5hak** [comment]
Ah, thank you so much for pointing this out. I will update the link.

**Comment by dar5hak** [comment]
Found the [new one!](https://github.com/RichardLitt/knowledge/blob/master/github/amending-a-commit-guide.md) 🎉
